ports:
  - port: 3306
    onOpen: ignore
    visibility: private
  - port: 33060
    onOpen: ignore
    visibility: private
  - port: 8001
    onOpen: ignore
    visibility: public
image: pookmish/drupal8ci:gitpod
tasks:
  - before: >
      eval $(command gp env -e) &&
      [[ ! -z $GITCONFIG  ]] &&
      echo $GITCONFIG | base64 -d > ~/.gitconfig &&
      chmod 644 ~/.gitconfig
    init: >
      gp await-port 3306 &&
      export PREVIEW_FULL_URL=`gp url 8001` &&
      export PREVIEW_URL=${PREVIEW_FULL_URL#"https://"} &&
      composer update --no-interaction &&
      drush si standard --db-url=mysql://root@localhost/drupal -y &&
      drush en admin_toolbar devel_php -y &&
      chmod -R 777 docroot/sites
    command: |
      apache2ctl restart
      git config core.fileMode false
