ports:
  - port: 3306
    onOpen: ignore
    visibility: private
  - port: 33060
    onOpen: ignore
    visibility: private
  - port: 8001
    onOpen: ignore
    visibility: public
image: pookmish/drupal8ci:gitpod
tasks:
  - before: >
      eval $(command gp env -e) &&
      mkdir -p ~/.ssh &&
      [[ ! -z $SSH_PUBLIC_KEY  ]] &&
      echo $SSH_PUBLIC_KEY | base64 -d > ~/.ssh/id_rsa.pub &&
      chmod 644 ~/.ssh/id_rsa.pub &&
      [[ ! -z $SSH_PRIVATE_KEY  ]] &&
      echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa &&
      chmod 600 ~/.ssh/id_rsa &&
      [[ ! -z $GITCONFIG  ]] &&
      echo $GITCONFIG | base64 -d > ~/.gitconfig &&
      chmod 644 ~/.gitconfig
    init: >
      export PREVIEW_FULL_URL=`gp url 8001` &&
      export PREVIEW_URL=${PREVIEW_FULL_URL#"https://"} &&
      composer install --no-interaction &&
      drush si standard --db=url=mysql://root@localhost/drupal -y &&
      chmod -R 777 web/sites
    command: |
      git remote set-url origin git@github.com:pookmish/drupal-tester.git
      apache2ctl restart
      gp await-port 8001
      git config core.fileMode false
